### ISSUE TITLE
A nice project

### ISSUE THREAD

**Issue by HuluWZ** [Umar-Saeed-97/Vehicle-In-Out-Count#1]
but better to add getting cars other info like plate no which helps to find when someone lost it

**Comment by Umar-Saeed-97** [comment]
While I appreciate the idea, the current camera feed or video is not zoomed in enough to capture number plates or read them accurately. As a result, adding this feature would not be feasible with the current setup. 

However, I will keep your suggestion in mind for future iterations of the project. 

Thank you!

**Comment by umarsaeedalam** [comment]
While I appreciate the idea, the current camera feed or video is not zoomed in enough to capture number plates or read them accurately. As a result, adding this feature would not be feasible with the current setup.

However, I will keep your suggestion in mind for future iterations of the project.

Thank you!
